#!/bin/bash
export HOSTNAME=transmission PORT=9091 
docker run --cap-add=NET_ADMIN \
              -v /mnt/disks/data/tranmission:/data \
              -v /etc/localtime:/etc/localtime:ro \
              -e CREATE_TUN_DEVICE=true \
              -e OPENVPN_PROVIDER=PIA \
              -e OPENVPN_CONFIG=Netherlands \
              -e OPENVPN_USERNAME=$PIA_USER \
              -e OPENVPN_PASSWORD=$PIA_PASS \
              -e WEBPROXY_ENABLED=false \
              -e LOCAL_NETWORK=$(docker network inspect traefik | jq -r '.[0].IPAM.Config[0].Subnet') \
              --log-driver json-file \
              --log-opt max-size=10m \
              haugene/transmission-openvpn
